import { Avatar } from './types';

export const avatars: Avatar[] = [
  {
    id: 1,
    name: "Matsya",
    sanskritName: "मत्स्य",
    title: "The Great Fish",
    color: "#006994",
    particlesColor: "#00BFFF",
    symbol: "Fish",
    description: "In the twilight of the first epoch, when dissolution threatened all creation, Lord Vishnu manifested as Matsya. He towed the ark of King Manu through the cosmic deluge, saving the sacred Vedas and the seeds of all life.",
    mantra: "ॐ मत्स्यरूपाय नमः",
    mantraTransliteration: "Om Matsyarupaya Namah",
    yuga: "Satya Yuga",
    lesson: "Divine guidance appears in unexpected forms to preserve wisdom."
  },
  {
    id: 2,
    name: "Kurma",
    sanskritName: "कूर्म",
    title: "The Cosmic Turtle",
    color: "#8B4513",
    particlesColor: "#CD853F",
    symbol: "Turtle",
    description: "During the churning of the cosmic ocean (Samudra Manthan), Vishnu became the giant tortoise Kurma to support the mountain Mandara on his back, allowing the gods and demons to extract the nectar of immortality.",
    mantra: "ॐ कूर्मरूपाय नमः",
    mantraTransliteration: "Om Kurmarupaya Namah",
    yuga: "Satya Yuga",
    lesson: "Steadfastness and stability are the foundations of great endeavors."
  },
  {
    id: 3,
    name: "Varaha",
    sanskritName: "वराह",
    title: "The Boar",
    color: "#DC143C",
    particlesColor: "#FF4500",
    symbol: "Boar",
    description: "When the demon Hiranyaksha dragged the Earth to the bottom of the cosmic ocean, Vishnu took the form of a boar to rescue her, lifting the planet on his tusks and restoring it to its orbit.",
    mantra: "ॐ वराहरूपाय नमः",
    mantraTransliteration: "Om Varaharupaya Namah",
    yuga: "Satya Yuga",
    lesson: "Righteous might must be used to uplift the fallen and protect the weak."
  },
  {
    id: 4,
    name: "Narasimha",
    sanskritName: "नरसिंह",
    title: "The Man-Lion",
    color: "#FF4500",
    particlesColor: "#FFA500",
    symbol: "Lion",
    description: "To defeat a demon who could not be killed by man or beast, inside or outside, day or night, Vishnu emerged from a pillar as a half-man, half-lion avatar at twilight to protect his devotee Prahlada.",
    mantra: "ॐ नरसिंहरूपाय नमः",
    mantraTransliteration: "Om Narasimharupaya Namah",
    yuga: "Satya Yuga",
    lesson: "God is omnipresent and will manifest to protect true devotion."
  },
  {
    id: 5,
    name: "Vamana",
    sanskritName: "वामन",
    title: "The Dwarf Brahmin",
    color: "#FFA500",
    particlesColor: "#FFD700",
    symbol: "Umbrella",
    description: "Vishnu appeared as a dwarf sage to curb the pride of King Bali. Asking for only three paces of land, he grew to cosmic size, covering the earth and heavens in two steps, and placing the third on Bali's head.",
    mantra: "ॐ वामनरूपाय नमः",
    mantraTransliteration: "Om Vamanarupaya Namah",
    yuga: "Treta Yuga",
    lesson: "Humility conquers pride; surrender leads to salvation."
  },
  {
    id: 6,
    name: "Parashurama",
    sanskritName: "परशुराम",
    title: "The Axe Wielder",
    color: "#C0C0C0",
    particlesColor: "#E0FFFF",
    symbol: "Axe",
    description: "Born to a sage, Parashurama wielded an axe to rid the world of corrupt warrior-kings who had abused their power and neglected their duties, re-establishing the social order.",
    mantra: "ॐ परशुरामरूपाय नमः",
    mantraTransliteration: "Om Parashuramarupaya Namah",
    yuga: "Treta Yuga",
    lesson: "Power without dharma leads to destruction and must be checked."
  },
  {
    id: 7,
    name: "Rama",
    sanskritName: "राम",
    title: "The Ideal King",
    color: "#228B22",
    particlesColor: "#90EE90",
    symbol: "Bow",
    description: "The prince of Ayodhya, Rama is the embodiment of dharma (righteousness). His journey to rescue his wife Sita and defeat the demon king Ravana is the subject of the epic Ramayana.",
    mantra: "ॐ रामचन्द्राय नमः",
    mantraTransliteration: "Om Ramachandraya Namah",
    yuga: "Treta Yuga",
    lesson: "Adherence to duty (Dharma) above personal desire creates a just society."
  },
  {
    id: 8,
    name: "Krishna",
    sanskritName: "कृष्ण",
    title: "The Divine Statesman",
    color: "#191970",
    particlesColor: "#4169E1",
    symbol: "Flute",
    description: "A playful cowherd, a divine lover, and a master strategist. Krishna delivered the Bhagavad Gita on the battlefield of Kurukshetra, teaching the yoga of devotion and duty.",
    mantra: "ॐ नमो भगवते वासुदेवाय",
    mantraTransliteration: "Om Namo Bhagavate Vasudevaya",
    yuga: "Dvapara Yuga",
    lesson: "Perform your duty without attachment to the results."
  },
  {
    id: 9,
    name: "Buddha",
    sanskritName: "बुद्ध",
    title: "The Enlightened One",
    color: "#FFFFFF",
    particlesColor: "#F8F8FF",
    symbol: "Lotus",
    description: "Born as Prince Siddhartha, he renounced worldly life to find the cause of suffering. As the Buddha, he taught non-violence (Ahimsa) and the path to Nirvana.",
    mantra: "ॐ बुद्धाय नमः",
    mantraTransliteration: "Om Buddhaya Namah",
    yuga: "Kali Yuga (Precursor)",
    lesson: "Compassion and non-violence are the highest truths."
  },
  {
    id: 10,
    name: "Kalki",
    sanskritName: "कल्कि",
    title: "The Future Warrior",
    color: "#8B00FF",
    particlesColor: "#DA70D6",
    symbol: "Sword",
    description: "Prophesied to appear at the end of the current Kali Yuga. Riding a white horse and wielding a blazing sword, Kalki will cleanse the world of unrighteousness and usher in a new Satya Yuga.",
    mantra: "ॐ कल्किरूपाय नमः",
    mantraTransliteration: "Om Kalkirupaya Namah",
    yuga: "End of Kali Yuga",
    lesson: "Time is cyclical; even the darkest night ends with a dawn."
  }
];

export const vishwaroopData: Avatar = {
  id: 0,
  name: "Vishwaroop",
  sanskritName: "विश्वरूप",
  title: "The Cosmic Form",
  color: "#FFD700",
  particlesColor: "#FFFFFF",
  symbol: "Lotus", // Generic symbol as placeholder, custom logic in modal might override
  description: "The Universal Form (Vishwaroop) is the supreme revelation of Lord Vishnu, containing all universes, time, life, and death within his body. Revealed to Arjuna in the Bhagavad Gita, it demonstrates that everything in existence is but a fragment of the Divine.",
  mantra: "ॐ नमो नारायणाय",
  mantraTransliteration: "Om Namo Narayanaya",
  yuga: "Eternal",
  lesson: "The entire cosmos is contained within the Divine; see God in everything."
};
